policies:
  - name: KerasPolicy
    epochs: 300
    max_history: 5
    batch_size : 50
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy